name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Setup conda
      uses: goanpeca/setup-miniconda@v1
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Apt-get packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get -y install libfftw3-dev

    - name: Brew packages
      if: matrix.os == 'macos-latest'
      run: |
        brew install fftw

    - name: Conda install dependencies
      shell: bash -l {0}
      run: |
        mamba install python=${{ matrix.python-version }} pip nodejs ipywidgets jupyter jupyterlab flake8 numpy cython

    - name: Install ipyleaflet
      shell: bash -l {0}
      run: pip install .

    - name: Install JupyterLab extension (Only on Linux for saving time)
      if: matrix.os == 'ubuntu-latest'
      shell: bash -l {0}
      run: jupyter labextension install js

    - name: Check installation files
      shell: bash -l {0}
      run: |
        test -d $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-leaflet
        test -f $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-leaflet/extension.js
        test -f $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-leaflet/index.js

    - name: Flake8 check
      shell: bash -l {0}
      run: flake8 psplay --ignore=E501,W503

    - name: Import check
      shell: bash -l {0}
      run: python -c 'import psplay'
