name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

defaults:
  run:
    shell: bash -l {0}

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge

    - name: Apt-get packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get -y install libfftw3-dev

    - name: Set gfortran link on macos-latest
      if: matrix.os == 'macos-latest'
      run: |
        set -x
        sudo ln -s /usr/local/bin/gfortran-10 /usr/local/bin/gfortran
        gfortran --version

    - name: Brew packages
      if: matrix.os == 'macos-latest'
      run: |
        brew install fftw

    - name: Conda install dependencies
      run: |
        mamba install python=${{ matrix.python-version }} pip nodejs ipywidgets jupyter jupyterlab flake8 numpy cython

    - name: Install psplay
      run: pip install .

    - name: Install JupyterLab extension (Only on Linux for saving time)
      if: matrix.os == 'ubuntu-latest'
      run: jupyter labextension install js

    - name: Check installation files
      run: |
        test -d $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-leaflet-car
        test -f $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-leaflet-car/extension.js
        test -f $CONDA_PREFIX/share/jupyter/nbextensions/jupyter-leaflet-car/index.js

    - name: Flake8 check
      run: flake8 psplay --ignore=E501,W503

    - name: Import check
      run: python -c 'import psplay'
